### ISSUE TITLE
Affichage anormal dans un module de vente si plusieurs produits identiques

### ISSUE THREAD

**Issue by AlexandrePalo** [borgia-app/Borgia#1]
## Description

Si une catégorie d'un module comporte plusieurs fois le même produit (c'est parfaitement faisable et géré par Borgia), par exemple Produit 1 vendu par 25cl et Produit 2 vendu par 50 cl, le comportement est anormal.

Lors de la sélection du produit dans le module de vente, par exemple si j'ajoute 1 au champ de sélection du produit 50 cl, c'est le produit 25 cl qui change et autres bugs.

Le problème ne semble concerner que l'affichage, et pas la vente réelle qui est créée et qui elle est parfaitement cohérente.

## Solution

Je pense que le problème vient du script javascript qui gère l'affichage des éléments achetés dans le module.

## Remarque

Apparait sur le module de vente en libre server ET par opérateur.

**Comment by Eyap53** [comment]
Fixed with #35.
