### ISSUE TITLE
Add the possibility to edit username

### ISSUE THREAD

**Issue by rowsky** [borgia-app/Borgia#104]
It is not possible now to edit username directly from the website.
This feature is needed in some cases where the registered username needs a correction.

**Comment by Eyap53** [comment]
Editable only by association managers, right ? Or even by the users themselves ?

**Comment by rowsky** [comment]
Only by association managers, in order to correct some input mistakes at registration

**Comment by Eyap53** [comment]
Ok, i will take care of it along #103

**Comment by Eyap53** [comment]
WIP with 347b6afc8d0ab9689744229bbf1a84768d0d2d0c.
I forgot to restrict the username change for normal users. I'll update it as soon as possible.

**Comment by Eyap53** [comment]
Fixed with df3d0f8
