### ISSUE TITLE
Add info on payments on shared events

### ISSUE THREAD

**Issue by Eyap53** [borgia-app/Borgia#13]
Add the number of participation in payment notification.

(Now, only the final amount is given)

**Comment by AlexandrePalo** [comment]
@Eyap53  closed by 8367a57b491bedc8858b67c4a65f2421a6551c31 ?

**Comment by Eyap53** [comment]
I thought i had answered this, sorry for the delay : 

With 8367a57, participants of the shared event have the price they were debited. (With a total price or with a price by weight). However, adding the number of weights (for each participant) in the description means changing the current way of handling the transaction description. 

In conclusion : I think it is **not a priority to solve this**, because a lot of work is needed for a small feature.
