### ISSUE TITLE
SharedEvent: See the total number of participation

### ISSUE THREAD

**Issue by Eyap53** [borgia-app/Borgia#14]
When the price by ponderation is determined before the event, it's difficult for the manager to set the total price to match that prevision.

What is wanted : Possibility to add the total number of ponderation in SharedEvent, to help the manager.
Another possibility is to allow the manager to chose the price by ponderation directly

**Comment by AlexandrePalo** [comment]
@Eyap53  closed by 8367a57b491bedc8858b67c4a65f2421a6551c31 ?

**Comment by Eyap53** [comment]
Yep, closed by 8367a57 !
