### ISSUE TITLE
Autocompletion username non cohérente

### ISSUE THREAD

**Issue by AlexandrePalo** [borgia-app/Borgia#2]
# Version 4.4 branche master & version à Siber's (Phabricator)

## Description

L'autocompletion des usernames est trop complexes. D'après un retour, il vaudrait mieux utiliser directement une recherche startswith avec le num's. Sinon il faut tapper toute la fam's ce qui est long pour 3 num's ... L'option recherche dans le mot ne va pas non plus sinon il y a trop de résultats.

Filtrer les résultats par ordre décroissant de promo (déjà le cas sur la version de github normalement).

**Comment by AlexandrePalo** [comment]
Closed by merging 7c8322cdefc0af5a800e5636c090bd265b3fbe4c.

**Comment by Eyap53** [comment]
Solved with pull request #3
