### ISSUE TITLE
Migration to Django 2.0

### ISSUE THREAD

**Issue by Eyap53** [borgia-app/Borgia#21]
# Migration to Django 2.0
## [Migration Guide](https://docs.djangoproject.com/en/2.0/releases/2.0/)

The principal change is the deprecation of python2, which we doesn't use. It should be as difficult as a migration of minor version.
Urls are quite modified as well.

**Comment by AlexandrePalo** [comment]
In order to show all warnings during the runserver, you can do:
`python3 -Wall manage.py runserver``
It shows every error and warning, especially warning concerning depreciation in the next version. So if you run that command with 1.11, you'll have depreciation warning in 2.0 :)

**Comment by AlexandrePalo** [comment]
Closed by 80f55d9f038aac21dc2ce42de7f16df60533d127.
