### ISSUE TITLE
Transaction history color

### ISSUE THREAD

**Issue by Eyap53** [borgia-app/Borgia#25]
Transaction history is all green for groups, like president and vice-president. 

For each transaction, info should be in red or green depending of the type (sale, ...)

**Comment by AlexandrePalo** [comment]
In self history ?

**Comment by Eyap53** [comment]
Nop, in history for another user. 

Example : You are the treasurer, and you want to check the history of someone. You will only have green lines in the history => By that i mean that every transaction is positive.

**Comment by AlexandrePalo** [comment]
Done :) #27

**Comment by AlexandrePalo** [comment]
Closed by 845ce0e4a2c24005b4e5de14437fa421bce40ce7.
