### ISSUE TITLE
Error for first inventory

### ISSUE THREAD

**Issue by Eyap53** [borgia-app/Borgia#37]
During the first inventory, a DivisionError is fired.

**Comment by AlexandrePalo** [comment]
HELLO

**Comment by Eyap53** [comment]
#Traceback

DoesNotExist at /chiefs-foys/stocks/inventories/create/
Inventory matching query does not exist.

http://127.0.0.1:8000/chiefs-foys/stocks/inventories/create/
1.11.4
DoesNotExist
Inventory matching query does not exist.
/usr/local/lib/python3.5/dist-packages/django/db/models/query.py in get, line 380
