### ISSUE TITLE
Fix permissions

### ISSUE THREAD

**Issue by Eyap53** [borgia-app/Borgia#47]
Fix some minor problems in the list of permission : 

- Some permissions have a "duplicate", such as "create évènement" and "ajouter évènement". Same problème with "Modify / Gérer".
- Some permissions lack french traduction. 
- The permissions are displayed in a huge list, without organisation. Maybe it is possible to regroup permissions under different labels in the forms ?

**Comment by GuillaumeBroggi** [comment]
I can take care of this one but I can't assign it to myself.
