### ISSUE TITLE
Translate and purify ReadMe

### ISSUE THREAD

**Issue by Eyap53** [borgia-app/Borgia#58]
# Translate and purify ReadMe
To be more appealing, the readme should be translated, and purified.

It can include some nice icon like these : 
[![GitHub](https://img.shields.io/badge/Github-issues-red.svg?maxAge=60)](https://github.com/borgia-app/Borgia/issues)
[![Slack](https://img.shields.io/badge/Slack-chat-green.svg?maxAge=60)](link-to-slack)

A listing of the principal features is necessary.
Info about contributing can be put in another file "Contributing.md". 

There should also be a more accessible link to the [documentation](https://github.com/borgia-app/Borgia-docs)

**Comment by AlexandrePalo** [comment]
Great idea !

**Comment by Eyap53** [comment]
Close issue for now. The ReadMe still need some purification and explanations of principal features, but it's not the current priority.
