### ISSUE TITLE
Autocompletion not working as intended

### ISSUE THREAD

**Issue by Eyap53** [borgia-app/Borgia#59]
- 1: It seems that autocompletion is not working as inteded anymore.
Intended behavior : See #3 

- 2 : Moreover, it seems that the query is case sensitive, which should not be.

- 3 : Lastly, finding users by first name may also not work, according to some managers. Further investigation needed.

**Comment by rowsky** [comment]
All these issues have a link with PostgreSQL database behavior that is different from MySQL or SQLite
- 1: The regex identifiers for PostgreSQL and SQLite are not the same
- 3: I believe it is just a result of the second point, they maybe don't know yet that queries are case sensitive.
