### ISSUE TITLE
Bad display link name in Login

### ISSUE THREAD

**Issue by AlexandrePalo** [borgia-app/Borgia#99]
## Issue

When you select a direct login link, for instance to a shop, the display name is no longer "humanizable" and understandable efficently.
This is the result of the new url pattern where there is no "group name".

<img width="555" alt="Capture d’écran 2019-09-08 à 20 59 20" src="https://user-images.githubusercontent.com/18114533/64493114-45c7a400-d27c-11e9-9395-7717001a92c3.png">

## Possible solution

Replace the display link by something me readable, for instance "Vente direct SHOP_NAME".

**Comment by rowsky** [comment]
Fixed for all shops' modules url ! Fixed by [f967a1e](https://github.com/borgia-app/Borgia/commit/f967a1e7f8a0ae81d2a1439dc3d9063acfafe62f)
Hope there is a better way to generalize this to all existing urls
